### ISSUE TITLE
Is there any support for requiring an address? 

### ISSUE THREAD

**Issue by johannbotha** [petersirka/node-paypal-express-checkout#11]
I don't seem to be asked to verify my address on account (when checking out). Can the initial call be configured to take a 'requireAddress' param?

**Comment by petersirka** [comment]
Hi @johannbotha,
can you send me a link to `paypal` documentation due to  param of `requireAddress`?

Thanks!

**Comment by johannbotha** [comment]
Hey @petersirka , I was thinking you could just add an option parameter and do something like
```
params.NOSHIPPING = self.address ? 0 : 1;
```
This will add the address prompt in paypal windows. 
https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/

**Comment by petersirka** [comment]
@johannbotha thanks, I'll add it :+1:

**Comment by johannbotha** [comment]
@petersirka I made a pull request that adds the field. 
#12

**Comment by petersirka** [comment]
Great, it will be better.

**Comment by petersirka** [comment]
I'll check + publish it into NPM.
Thanks.
